examples/create-batch-proposal/index.js, examples/create-proposal/index.js, packages/deploy/README.md, packages/deploy/src/models/approval-process.ts, packages/proposal/src/models/proposal.ts
https://linear.app/openzeppelin-development/issue/PLAT-2497/rename-all-occurrences-from-gnosis-safe-safe
=> Replace Gnosis viaTypes by Safe

examples/create-forked-network/index.js, package.json, packages/relay-signer/src/models/relayer.ts, packages/relay-signer/src/models/transactions.ts, packages/relay-signer/src/relayer.ts
pnpm nx-build-test-skip-cache command was failing due to parallel building, some packages depend on base to build properly, so I changed secuential builds, this is slower but seems to be necesary.
cc @tirumerla
=> enforce base package to build first

examples/get-usage/index.js, examples/get-usage/package.json, packages/account/README.md, packages/account/jest.config.js, packages/account/package.json, packages/account/src/api/index.ts, packages/account/src/index.ts, packages/account/src/models/account.ts, packages/account/tsconfig.json, packages/defender-sdk/src/index.ts, pnpm-lock.yaml
This PR will allow users to retrieve their account usage.
New defender-sdk client `account` was added as holder for this logic.
Parent PR: https://github.com/OpenZeppelin/defender/pull/4908
=> Add support for retrieving account usage via sdk

examples/deploy-contract/artifacts/Box.json, examples/deploy-contract/contracts/Box.sol, examples/deploy-contract/index.js, examples/deploy-contract/package.json, packages/deploy/README.md, packages/deploy/src/models/deployment.ts, pnpm-lock.yaml
Support for custom constructor bytecode.
```ts
const deployment = await client.deploy.deployContract({
contractName: 'Box',
contractPath: 'contracts/Box.sol',
network: 'sepolia',
artifactPayload: JSON.stringify(artifactFile),
licenseType: 'MIT',
verifySourceCode: true,
constructorBytecode: AbiCoder.defaultAbiCoder().encode(['uint'],['5']), // or constructorInputs: [5],
});
```
=> Defender deploy support constructor input as an abi encoded

packages/relay-signer/src/ethers/signer.ts
Networks that don't support ENS by default, such as base-sepolia or arbitrum-sepolia, would fail in transactions using ethers signer when `to` parameter is set, because previous logic assumes that resolveEns would fail gracefully when it actually throws an error.
New logic should delegate the ENS resolution to `resolveAddress` function in ethers v6 
https://linear.app/openzeppelin-development/issue/PLAT-4392/relay-signer-failing-to-send-transaction-when-used-in-ethers-v6
=> relaySigner: avoid resolving ENS name by default

packages/defender-sdk/src/index.ts
Adds the possibility to set a custom httpsAgent configs for client packages
Example:
```js
const client = new Defender({ 
apiKey: process.env.API_KEY,
apiSecret: process.env.API_SECRET, 
httpsAgent: https.Agent({ keepAlive: true }) 
});
```
=> Include httpsAgent param in client packages

packages/base/package.json, packages/base/src/action/index.ts, packages/base/src/utils/lambda.ts, packages/relay-signer/src/__mocks__/@aws-sdk/client-lambda.ts, packages/relay-signer/src/action/index-rate.test.ts, packages/relay-signer/src/action/index.test.ts, pnpm-lock.yaml
Still requires some refactor/cleanup, I succesfully tested this logic running the following action and switching runtime in AWS console
```js
const { version } = require('node:process');
exports.handler = async function(credentials, context) {
const creds = JSON.parse(credentials.credentials);
console.log("node version", version);
let lambda;
let result;
if (version >= 'v20.0.0') {
const { Lambda } = require('@aws-sdk/client-lambda');
lambda = new Lambda({
credentials: {
accessKeyId: creds.AccessKeyId,
secretAccessKey: creds.SecretAccessKey,
sessionToken: creds.SessionToken,
},
});
result = await lambda.invoke({
FunctionName: '< relayer proxy arn >',
Payload: JSON.stringify({ action: 'get-self-status' }),
InvocationType: 'RequestResponse',
});
result.Payload = …
```
=> Add conditional import for aws lambda package

examples/custom-ethers-pkg/rollup.config.ts, examples/custom-ethers-pkg/src/index.ts
Defender Actions don't support ES module syntax at this time, thus the example will not work. Changing output to CommonJS fixes this
=> Change Output Format of Custom Ethers Example to CJS

packages/base/src/api/client.ts, packages/defender-sdk/src/index.ts
https://linear.app/openzeppelin-development/issue/PLAT-4889/enable-credentials-caching-by-default-for-latest-version-of-defender
=> Optimise api access by default

packages/relay-signer/package.json, pnpm-lock.yaml
This PR will add @ethersproject/providers to dependencies section as this package includes all needed packages in order for ethers-v5 and providers-v5 files to work.
https://linear.app/openzeppelin-development/issue/PLAT-5016/fix-defender-sdk-relayer-signer-package
=> fix: Add missing dependencies that caused relay signer to fail

examples/create-private-network/index.js, packages/network/src/api/index.test.ts, packages/network/src/api/index.ts, packages/network/src/models/networks.ts
Adds support to `isProduction` flag when creating private networks to define the environment of the network.
=> feat: Add support to isProduction flag for private networks

packages/deploy/src/models/deployment.ts, packages/deploy/src/utils/deploy.test.ts, packages/deploy/src/utils/deploy.ts
https://linear.app/openzeppelin-development/issue/PLAT-5322/fix-missing-deployedbytecode-artifact
=> fix(deploy): include deployed bytecode to artifact

packages/account/src/api/index.ts, packages/action/src/api.ts, packages/deploy/src/api/index.ts, packages/network/src/api/index.ts, packages/proposal/src/api/index.ts, packages/relay-signer/src/api/index.ts, packages/relay-signer/src/ethers/provider-v5.ts, packages/relay-signer/src/ethers/provider.ts, packages/relay/src/api/index.ts
Removes /v2/ base path in most packages exept blockwatchers and notifiacitons (they are not supported in root basepath)
=> fix: remove /v2 from basepath in most packages

e2e/package.json
- Looks like npm publish is failing due to not setting private for e2e as it's added to workspace.
=> fix: set private true for e2e

e2e/src/address-book.test.ts, examples/address-book-actions/index.js, examples/address-book-actions/package.json, packages/address-book/README.md, packages/address-book/jest.config.js, packages/address-book/package.json, packages/address-book/src/api/index.ts, packages/address-book/src/index.ts, packages/address-book/src/models/address-book.ts, packages/address-book/tsconfig.json, packages/defender-sdk/package.json, packages/defender-sdk/src/index.ts, pnpm-lock.yaml
Adds new sub-package `addressBook` to list, create and delete address book entries.
> Important: we must change the E2E API key to support the new capabilities (manage-address-book)
Included in e2e
=> feat: add address book client methods

examples/custom-ethers-pkg/src/index.ts, packages/relay-signer/src/relayer.ts
Fixes typescript lint error when using ethers provider and signer
=> fix: type inference in relay signer

examples/update-deployment/artifacts/Box.json, examples/update-deployment/contracts/Box.sol, examples/update-deployment/index.js, examples/update-deployment/package.json, packages/deploy/src/api/index.ts, packages/deploy/src/models/deployment.ts, pnpm-lock.yaml
Exposing deployment update API for cases where users create a deployment environment and then sign and deploy a contract using an external provider (e.g. Metamask from Remix site). We want the ability to sync Defender deploy environment with the latest changes including deployed contract info (address + transaction hash).
=> feat: support update deployments

packages/deploy/src/models/deployment.ts, packages/deploy/src/utils/deploy.test.ts, packages/deploy/src/utils/deploy.ts
Includes `immutableReferences` object from the build data when extracting the artifact data necessary for the deploy with Defender.
`immutableReferences` object is used to locate any slots that need to be considered when comparing and verifying on-chain bytecode with the `deployedBytecode` from the artifact. For example immutable variables are used in upgradeable contracts and their proxies depending on the type of the upgradeable contract.
This PR will fix an existing issue with Defender not being able to verify bytecodes of the contracts that use immutable variables.
=> feat(deploy): include immutableReferences in extracted artifact

examples/eas-relayer-signer/package.json, examples/eas-relayer-signer/src/index.ts, examples/eas-relayer-signer/tsconfig.json
Creates a new example in the repository that demonstrates how to use the Ethereum Attestation Service with a Defender Relay Signer
=> docs(examples): adds new example to repo

packages/deploy/src/api/deployment.test.ts, packages/deploy/src/api/index.ts, packages/deploy/src/models/deployment.ts
Add `origin` attribute to deployments to detect the client origin that sent the deployment request
=> feat: add attribute to detect the deployment origin

packages/base/package.json, pnpm-lock.yaml
- This PR will add `@aws-sdk/client-lambda` to dependencies section as this package is being used by defender-sdk package and the users expect this package to be part of the dependencies by default.
=> fix: client lambda dependencies with actions example

packages/base/src/utils/network.ts
=> fix: PLAT-6229 Adding custom name for peaq inside sdk

packages/deploy/src/models/deployment.ts, packages/deploy/src/utils/deploy.test.ts, packages/deploy/src/utils/deploy.ts
When verifying contract on Etherscan the content source code content of the dependency of the contract are required alongside the contract's source code content.
=> fix(deploy): PLAT-6273 Add all input sources for dependency validation

package.json, packages/defender-sdk/src/index.ts, packages/network/src/api/index.test.ts, packages/network/src/api/index.ts, packages/network/src/index.ts, packages/network/src/models/networks.ts
Adjust typing to support "deploy" network type (will be used in deploy plugin to filter out networks that do not support deployment by Defender
=> feat(Deploy-BE): PLAT-6398 include deploy network type

packages/proposal/src/models/proposal.ts
This PR adds clear documentation to distinguish between "Gnosis Multisig" and "Safe" in the `viaType` property of the `ExternalApiCreateProposalRequest` interface. The JSDoc comments now properly explain:
- 'EOA'              : An externally owned account          (hot wallet)
- 'Safe'             : A Safe multi-signature wallet        (formerly Gnosis Safe)
- 'Gnosis Multisig'  : A legacy Gnosis multi-signature wallet      (not Safe)
- 'Relayer'          : A Defender Relayer                  (cloud signer)
This addresses issue [#553](https://github.com/OpenZeppelin/defender-sdk/issues/553) where users needed clarity on the difference between these wallet options.
Documentation-only change. Manual verification performed to ensure:
- Proper JSDoc formatting
- Clear distinction between …
=> docs(proposals): Clarify distinction between Safe and Gnosis Multisig viaType options (#553)
