OpenZeppelin/defender-sdk

.github/workflows/codeql.yml
.github/workflows/scorecard.yml

- Update scorecard & CodeQL analysis

Update scorecard & codeql configs

---

examples/update-action/index.js
examples/update-action/package.json

Added example to update action name

add update action example

---

.changeset/strong-pandas-run.md

Add changeset file

---

examples/create-forked-network/index.js
examples/create-forked-network/package.json
pnpm-lock.yaml

This PR will add forked network example.

Add forked network example

---

.changeset/three-teachers-share.md

- Adds the changeset file for the 12/10/2023 release

Add  changeset file

---

packages/deploy/src/models/approval-process.ts
packages/deploy/src/models/deployment.ts

https://linear.app/openzeppelin-development/issue/PLAT-3029/deploy-safe-eoa-apply-model-changes-to-defender-sdk

Change `componentType` model for approval process

---

packages/base/src/utils/network.ts

https://linear.app/openzeppelin-development/issue/PLAT-3098/support-for-scroll-network-[mainnet]

Add support to scroll mainnet

---

examples/list-proposals/CHANGELOG.md
examples/list-proposals/index.js
examples/list-proposals/package.json
packages/proposal/src/api/index.ts
packages/proposal/src/models/proposal.ts
pnpm-lock.yaml

Support pagination in proposals list endpoint + add example
https://linear.app/openzeppelin-development/issue/PLAT-2723/defender-sdk-pagination-support-for-transaction-proposals

Support pagination for proposals and add example

---

packages/deploy/src/models/deployment.ts

Merge after: https://github.com/OpenZeppelin/defender/pull/4934

Add createFactoryAddress optional parameter to deploy request

---

packages/base/src/utils/network.ts

https://linear.app/openzeppelin-development/issue/PLAT-3238/add-meld-network-string-to-defender-sdk

Add Meld network

---

.changeset/mean-chairs-tap.md
pnpm-lock.yaml

- Add new changeset file for release of v1.5.0

add v1.5.0 changeset

---

packages/monitor/src/__mocks__/@openzeppelin/defender-sdk-base-client.ts
packages/monitor/src/api/index.test.ts
packages/monitor/src/api/index.ts

https://linear.app/openzeppelin-development/issue/PLAT-3327/expose-tenant-block-watcher-in-sdk

Add list tenant block watchers endpoint

---

packages/base/src/utils/network.ts

Add support to Arbitrum sepolia testnet

add arbitrum sepolia

---

.changeset/plenty-bobcats-bathe.md

- Add changeset file for 1.6.0

Add changeset file for 1.6.0

---

packages/deploy/src/api/index.ts
packages/deploy/src/fixtures/Box.json
packages/deploy/src/models/deployment.ts
packages/deploy/src/utils/deploy.test.ts
packages/deploy/src/utils/deploy.ts

Artifact optimization to enable deployment even in conditions of big contract outputs.
https://linear.app/openzeppelin-development/issue/PLAT-3458/optimize-deploy-sdk

Optimize deployment

---

packages/proposal/src/api/index.ts

https://linear.app/openzeppelin-development/issue/PLAT-3214/proposalclientsimulate-expects-transactiondata-parameter

Rename simulation transaction type

---

.changeset/tasty-walls-return.md

Add the changelog file for 1.8.0 release

Add the changelog file for 1.8.0 release

---

examples/list-contracts/package.json
examples/update-action-env-variables/package.json
pnpm-lock.yaml

Update package dependencies

---

.changeset/wild-moons-ring.md

- Add changeset file for 1.9.0

Add changeset file for 1.9.0

---

packages/deploy/src/models/deployment.ts

merge after https://github.com/OpenZeppelin/defender/pull/5453

Add confirmations prop to tx override

---

.changeset/serious-candles-end.md

Add changeset for new release

---

packages/base/src/utils/network.ts

Remove Optimism Goerli network as we're deprecating it

Remove Optimism goerli network as we're deprecating it

---

packages/base/src/utils/network.ts

Merge after: https://github.com/OpenZeppelin/defender/pull/5643
https://linear.app/openzeppelin-development/issue/PLAT-4329/add-holesky-network-to-sdk

Add Holesky network

---

examples/create-action/index.js
examples/create-batch-proposal/index.js
examples/create-forked-network/index.js
examples/create-monitor/index.js
examples/create-private-network/index.js
examples/create-proposal/index.js
examples/create-relayer-key/index.js
examples/create-relayer/index.js
examples/deploy-contract/index.js
examples/ethers-signer/index.js
examples/get-usage/index.js
examples/list-contracts/index.js
examples/list-networks/index.js
examples/list-proposals/index.js
examples/relayer-web3-provider/index.js
examples/simulate-proposal/index.js
examples/update-action-env-variables/index.js
examples/update-action/index.js
examples/update-action/update-code.js
examples/update-monitor/index.js
examples/update-relayer/index.js
examples/upgrade-contract/index.js
pnpm-lock.yaml

Add httpsAgent to examples

---

examples/create-action/index.js
examples/create-batch-proposal/index.js
examples/create-forked-network/index.js
examples/create-monitor/index.js
examples/create-proposal/index.js
examples/create-relayer-key/index.js
examples/create-relayer/index.js
examples/deploy-contract/index.js
examples/ethers-signer/index.js
examples/get-usage/index.js
examples/list-contracts/index.js
examples/list-networks/index.js
examples/list-proposals/index.js
examples/relayer-web3-provider/index.js
examples/simulate-proposal/index.js
examples/update-action-env-variables/index.js
examples/update-action/index.js
examples/update-action/update-code.js
examples/update-monitor/index.js
examples/update-relayer/index.js
examples/upgrade-contract/index.js
pnpm-lock.yaml
pnpm-workspace.yaml

Import https to fix examples

---

package.json
packages/base/src/utils/network.test.ts
packages/base/src/utils/network.ts

Merge after https://github.com/OpenZeppelin/defender/pull/5748
- Adds support for Amoy testnet

Add support to amoy

---

.changeset/sharp-pianos-glow.md

Add new changeset file for v1.12.0

---

.changeset/seven-apricots-carry.md
examples/create-batch-proposal/index.js
examples/create-monitor/index.js
examples/create-proposal/index.js
examples/create-relayer/index.js
examples/upgrade-contract/index.js
packages/base/src/utils/network.test.ts
packages/base/src/utils/network.ts
packages/deploy/src/api/block-explorer-api-key.test.ts
packages/deploy/src/api/deployment.test.ts
packages/monitor/src/api/index.test.ts
packages/relay-signer/src/ethers/signer.test.ts
packages/relay-signer/src/web3/sender.test.ts

deprecate goerli (+ zksync, base, arbitrum, optimism)

deprecate goerli (+ zksync, base, arbitrum, optimism)

---

examples/relayer-load-balance/CHANGELOG.md
examples/relayer-load-balance/index.js
examples/relayer-load-balance/package.json
pnpm-lock.yaml

https://linear.app/openzeppelin-development/issue/PLAT-4541/add-load-balance-example-to-sdk

Add load balance example

---

packages/relay-signer/src/ethers/signer.ts
packages/relay-signer/src/models/relayer.ts
packages/relay-signer/src/models/transactions.ts
packages/relay-signer/src/web3/sender.ts
packages/relay/src/models/index.ts

https://linear.app/openzeppelin-development/issue/PLAT-4542/support-flashbots-fast-in-defender-sdk

Support flashbots fast in defender sdk

---

packages/relay/src/models/index.ts

Add stackId in update relayer request

add stackId in update relayer request

---

.changeset/chatty-kangaroos-move.md
.github/actions/prepare/action.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/publish.yml
.github/workflows/rc.yml
.github/workflows/release.yml
.github/workflows/scorecard.yml
.github/workflows/stable.yml
.github/workflows/version.yml

- Update actions version for ci
- Prepare for new release

Update ci actions versions & prepare for new release

---

examples/send-4337-userop/account-kit/index.js
examples/send-4337-userop/account-kit/package.json
examples/send-4337-userop/permissionless/package.json
examples/send-4337-userop/permissionless/safe.js

This PR adds usage examples of Defender Relay used as an ERC4337 signer to relay user operations.

Add ERC4337 signer examples

---

.changeset/soft-pears-turn.md

add changeset for 1.13.4

---

packages/relay/src/models/index.ts

This PR will extend relayer update type to support webhook notification fields.

Update relayer update type

---

examples/relayer-signer-actions/index.js
packages/relay-signer/src/api/index.ts
packages/relay-signer/src/models/transactions.ts

This PR will only allow tx pagination option to be used for new package versions.

Use tx pagination option by default

---

.gitignore
examples/relayer-web3-provider/package.json
examples/update-monitor/package.json
package.json
packages/relay-signer/package.json
pnpm-lock.yaml

- Fix vulnerabilities & bump web3 minor version
Will tackle web3 upgrade to v4 in the next pr.

Fix vulnerabilities from dependabot and bump web3 minor

---

.pre-commit-config.yaml
hack/sortNetworks.js
package.json
packages/base/src/utils/network.ts

Add sort networks script to pre-commit

---

.github/workflows/version-or-publish.yml
package.json
pnpm-lock.yaml
scripts/release.js

- Add a workflow to automate the package release

Add an automation release workflow

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/actions/prepare/action.yml
.github/dependabot.yml
.github/pr-title-checker-config.json
.github/pull_request_template.md
.github/workflows/pr-title.yml
CODEOWNERS
README.md
package.json
packages/relay-signer/src/api/index.ts
pnpm-lock.yaml

- Current pnpm version we are seeing issues when running ci pipelines especially when lockfile is being used. 
https://github.com/pnpm/pnpm/issues/7184
- Upgrade pnpm version to v9

chore: upgrade pnpm

---

.github/workflows/ci.yml
README.md

- Run ci tests after merge to main
- Add openssf best practices badge to sync it correctly
N/A

chore: Bring back openssf badge

---

packages/relay-signer/src/api/index.ts

Previously overwritten by merge conflict.

fix: Revert merge overwritten change

---

examples/upgrade-contract-uups/README.md
examples/upgrade-contract-uups/abis/UUPSOwnable.json
examples/upgrade-contract-uups/index.js
examples/upgrade-contract-uups/package.json
pnpm-lock.yaml

Added example to showcase a simple UUPS contract upgrade using Defender

docs: add uups upgrade example

---

packages/base/src/utils/network.ts

Adds support to linea sepolia network

fix: add support to linea sepolia

---

packages/proposal/src/api/utils.ts

Update transaction proposal route

refactor(transaction-proposals): update transaction proposal route

---

examples/deploy-contract/index.js
packages/deploy/src/models/deployment.ts

Adds new field to include any desired metadata to deployment

feat: add support to deployment metadata

---

examples/relayer-signer-actions/index.js
packages/relay-signer/src/action/index.test.ts
packages/relay-signer/src/action/index.ts
packages/relay-signer/src/api/index.ts
packages/relay-signer/src/models/relayer.ts
packages/relay-signer/src/models/transactions.ts
packages/relay-signer/src/relayer.ts

https://linear.app/openzeppelin-development/issue/PLAT-5060/add-support-for-cancelling-intents-in-sdk

feat: add support for cancelling intents

---

.github/dependabot.yml
.github/workflows/publish-snapshot.yml
.github/workflows/publish.yml
.pre-commit-config.yaml
.pre-commit-hooks.yaml

- Fix pr titles to follow conventional commits
- Add precommit 
- Allow provenance attachment for npm publishes.

fix: automated pr titles

---

.github/workflows/publish.yml

- Resolve issue with attestation publishing
- 
- Run the publish workflow to verify that the attestations are indeed being published.

fix: Resolve issue with attestation publishing

---

examples/create-relay-group/index.js
examples/create-relay-group/package.json
pnpm-lock.yaml

Fixes little issues with create relay group example

fix: relayer groups create example

---

.changeset/slow-days-scream.md

Adds the v1.15.0 changeset file

chore: Add v1.15.0 changeset file

---

.github/workflows/publish.yml

fix: Fix NPM provenance

---

examples/relayer-signer-actions/index.js
packages/relay-signer/README.md
packages/relay-signer/src/action/index.ts
packages/relay-signer/src/api/index.ts
packages/relay-signer/src/models/relayer.ts
packages/relay-signer/src/relayer.ts

Add relayer-signer `getTransactionByNonce` method to enable fetching transaction by nonce.

feat(txs-nonce): Add support to query transactions by nonce

---

packages/relay-signer/src/action/index.test.ts
packages/relay-signer/src/action/index.ts

https://linear.app/openzeppelin-development/issue/PLAT-5532/fix-sdk-relay-signer-action-payloads

fix(payloads): fix payload format for relay-signer

---

.changeset/fluffy-icons-approve.md

chore: Add v1.15.1 changelog file

---

packages/base/src/utils/network.ts

https://linear.app/openzeppelin-development/issue/PLAT-6109/add-peaq-as-a-formally-supported-defender-network

feat: PLAT-6109 Adding support for Peaq network

---

packages/base/src/utils/network.ts

feat: Add unichain network

---

packages/base/src/utils/network.ts

This reverts commit bcfcedfe8007156d5fc050e5da412056d2e8e2aa.
- Revert support for Peaq network

revert: Revert "feat: PLAT-6109 Adding support for Peaq network (#687)"

---

packages/base/src/utils/network.ts

https://linear.app/openzeppelin-development/issue/PLAT-6111/add-support-for-abstract-chain

feat: Add Abstract support

---

examples/create-monitor/index.js
examples/update-monitor/index.js
packages/action/src/models/action-event-utils.ts
packages/monitor/src/api/index.test.ts
packages/monitor/src/api/index.ts
packages/monitor/src/models/monitor.ts
packages/monitor/src/models/response.ts

Defender is sunsetting its Forta integration.

feat(forta): remove forta integration

---

.changeset/dirty-foxes-burn.md

chore: add v2.6.0 changeset file

---

packages/base/src/utils/network.ts

feat: Adding support for Sei chain
